export const enum QueriesKeysEnum {
  appleAuth = 'appleAuth',
  appleAuthCallback = 'appleAuthCallback',
  coinbaseAuth = 'coinbaseAuth',
  coinbaseAuthCallback = 'coinbaseAuthCallback',
  discordAuth = 'discordAuth',
  discordAuthCallback = 'discordAuthCallback',
  facebookAuthUrl = 'facebookAuthUrl',
  facebookAuthUrlCallback = 'facebookAuthUrlCallback',
  githubAuth = 'githubAuth',
  githubAuthCallback = 'githubAuthCallback',
  googleAuth = 'googleAuth',
  googleAuthCallback = 'googleAuthCallback',
  linkedInAuth = 'linkedInAuth',
  linkedInAuthCallback = 'linkedInAuthCallback',
  telegramAuth = 'telegramAuth',
  telegramAuthCallback = 'telegramAuthCallback',
  twitterAuth = 'twitterAuth',
  twitterAuthCallback = 'twitterAuthCallback',
  redditAuth = 'redditAuth',
  redditAuthCallback = 'redditAuthCallback',
  worldIdAuth = 'worldIdAuth',
  worldIdAuthCallback = 'worldIdAuthCallback',
  tikTokAuth = 'tikTokAuth',
  tikTokAuthCallback = 'tikTokAuthCallback',
}
